import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, Alert, ScrollView } from 'react-native';
import { getDb } from '../db/db';
import { uuid } from '../utils/uuid';

export default function CbtFormScreen({ route, navigation }) {
  const { student } = route.params;
  const [sessionName, setSessionName] = useState('');
  const [qty, setQty] = useState('1');
  const [saving, setSaving] = useState(false);

  const handleSave = async () => {
    if (!sessionName.trim()) {
      Alert.alert('Missing info', 'Enter a session name (e.g. "JAMB Mock 1").');
      return;
    }
    setSaving(true);
    try {
      const db = await getDb();
      await db.runAsync(
        `INSERT INTO pending_cbt (client_uuid, reg_no, session_name, qty) VALUES (?,?,?,?)`,
        [uuid(), student.reg_num, sessionName.trim(), parseInt(qty, 10) || 1]
      );
      setSaving(false);
      Alert.alert(
        'Saved offline',
        'The actual code(s) will be generated by the server once you sync (codes need to be unique, so they can\'t be created offline).',
        [{ text: 'OK', onPress: () => navigation.navigate('Home') }]
      );
    } catch (e) {
      setSaving(false);
      Alert.alert('Could not save', e.message);
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={{ padding: 16 }}>
      <View style={styles.studentBanner}>
        <Text style={styles.studentName}>{student.lname} {student.fname}</Text>
        <Text style={styles.studentMeta}>{student.reg_num} · {student.admitted_class}</Text>
      </View>

      <Text style={styles.fieldLabel}>Session name</Text>
      <TextInput style={styles.input} value={sessionName} onChangeText={setSessionName} placeholder="e.g. JAMB Mock 1" />

      <Text style={styles.fieldLabel}>How many codes</Text>
      <TextInput style={styles.input} value={qty} onChangeText={setQty} keyboardType="numeric" />

      <TouchableOpacity style={styles.submitBtn} onPress={handleSave} disabled={saving}>
        <Text style={styles.submitText}>{saving ? 'Saving…' : 'Queue CBT Code Request'}</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  studentBanner: { backgroundColor: '#f0f4fa', borderRadius: 10, padding: 14, marginBottom: 16 },
  studentName: { fontSize: 17, fontWeight: '700' },
  studentMeta: { fontSize: 13, color: '#666', marginTop: 2 },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: '#444', marginBottom: 4, marginTop: 12 },
  input: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, fontSize: 15 },
  submitBtn: { backgroundColor: '#1a3c6e', borderRadius: 10, padding: 16, alignItems: 'center', marginTop: 24, marginBottom: 40 },
  submitText: { color: '#fff', fontSize: 16, fontWeight: '700' },
});
